version: '3.3'

services:
  postgres:
    hostname: postgres
    image: postgres:13.0
    ports:
      - "5435:5432"
    expose:
      - "5435"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    restart: on-failure
    networks:
      - gulfstream
